// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC92g0OUN9i-F0nZOFnPQaoQETu40Dp62I',
    appId: '1:687447079571:web:1dbe8ed06d9ed626faab66',
    messagingSenderId: '687447079571',
    projectId: 'plantbook-efe67',
    authDomain: 'plantbook-efe67.firebaseapp.com',
    storageBucket: 'plantbook-efe67.firebasestorage.app',
    measurementId: 'G-D6JF8ERKQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDDaXEwozoiBXNBOQZBXPIFCBWna6JxU',
    appId: '1:687447079571:android:b083ef153de5a520faab66',
    messagingSenderId: '687447079571',
    projectId: 'plantbook-efe67',
    storageBucket: 'plantbook-efe67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFx75DgS3uxrIndp9dZ2-58HZmczLWiuc',
    appId: '1:687447079571:ios:66110de139ba4df7faab66',
    messagingSenderId: '687447079571',
    projectId: 'plantbook-efe67',
    storageBucket: 'plantbook-efe67.firebasestorage.app',
    iosBundleId: 'com.example.plantBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFx75DgS3uxrIndp9dZ2-58HZmczLWiuc',
    appId: '1:687447079571:ios:66110de139ba4df7faab66',
    messagingSenderId: '687447079571',
    projectId: 'plantbook-efe67',
    storageBucket: 'plantbook-efe67.firebasestorage.app',
    iosBundleId: 'com.example.plantBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC92g0OUN9i-F0nZOFnPQaoQETu40Dp62I',
    appId: '1:687447079571:web:d710ce61e0f039a5faab66',
    messagingSenderId: '687447079571',
    projectId: 'plantbook-efe67',
    authDomain: 'plantbook-efe67.firebaseapp.com',
    storageBucket: 'plantbook-efe67.firebasestorage.app',
    measurementId: 'G-3T9ZM6HSDK',
  );
}
