// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe1f1vKlfe6LPSiepkm5uZBwXidDvRVDU',
    appId: '1:1099340900582:web:6609f317918aa39cf7f327',
    messagingSenderId: '1099340900582',
    projectId: 'plantbook-f4042',
    authDomain: 'plantbook-f4042.firebaseapp.com',
    storageBucket: 'plantbook-f4042.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7VKzQrg9IRkL9Ko_n-G4_hV4HPHzAjnk',
    appId: '1:1099340900582:android:70709ee5cbcac74af7f327',
    messagingSenderId: '1099340900582',
    projectId: 'plantbook-f4042',
    storageBucket: 'plantbook-f4042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMUX4y1xwTbEK1OS7J6y0kXgcibCgKlNw',
    appId: '1:1099340900582:ios:bbc70f51aa03106bf7f327',
    messagingSenderId: '1099340900582',
    projectId: 'plantbook-f4042',
    storageBucket: 'plantbook-f4042.firebasestorage.app',
    iosBundleId: 'com.example.plantBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMUX4y1xwTbEK1OS7J6y0kXgcibCgKlNw',
    appId: '1:1099340900582:ios:bbc70f51aa03106bf7f327',
    messagingSenderId: '1099340900582',
    projectId: 'plantbook-f4042',
    storageBucket: 'plantbook-f4042.firebasestorage.app',
    iosBundleId: 'com.example.plantBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe1f1vKlfe6LPSiepkm5uZBwXidDvRVDU',
    appId: '1:1099340900582:web:4b3fb9fe4737f469f7f327',
    messagingSenderId: '1099340900582',
    projectId: 'plantbook-f4042',
    authDomain: 'plantbook-f4042.firebaseapp.com',
    storageBucket: 'plantbook-f4042.firebasestorage.app',
  );
}
